name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build iOS
        run: |
          xcodebuild \
            -project "CashApp-main/Cash App.xcodeproj" \
            -scheme "CashappSpoof" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            build
